import './style.css'

const teams = [['אלבניה','🇦🇱'],['אלג׳יריה','🇩🇿'],['אנגליה','🏴'],['אנגולה','🇦🇴'],['אנדורה','🇦🇩'],['אוסטריה','🇦🇹'],['אוסטרליה','🇦🇺'],['אוקראינה','🇺🇦'],['אורוגוואי','🇺🇾'],['אוזבקיסטן','🇺🇿'],['אזרבייג׳ן','🇦🇿'],['איחוד האמירויות','🇦🇪'],['איטליה','🇮🇹'],['אינדונזיה','🇮🇩'],['איסלנד','🇮🇸'],['איראן','🇮🇷'],['אירלנד','🇮🇪'],['אל סלבדור','🇸🇻'],['ארגנטינה','🇦🇷'],['ארמניה','🇦🇲'],['ארצות הברית','🇺🇸'],['אסטוניה','🇪🇪'],['אקוודור','🇪🇨'],['בולגריה','🇧🇬'],['בוליביה','🇧🇴'],['בוסניה והרצגובינה','🇧🇦'],['בלגיה','🇧🇪'],['בלארוס','🇧🇾'],['ברזיל','🇧🇷'],['גאנה','🇬🇭'],['גאורגיה','🇬🇪'],['גבון','🇬🇦'],['גואטמלה','🇬🇹'],['גרמניה','🇩🇪'],['דנמרק','🇩🇰'],['דרום אפריקה','🇿🇦'],['דרום קוריאה','🇰🇷'],['הודו','🇮🇳'],['הולנד','🇳🇱'],['הונדורס','🇭🇳'],['הונגריה','🇭🇺'],['ונצואלה','🇻🇪'],['ויילס','🏴'],['וייטנאם','🇻🇳'],['יוון','🇬🇷'],['יפן','🇯🇵'],['ישראל','🇮🇱'],['כווית','🇰🇼'],['כף ורדה','🇨🇻'],['לבנון','🇱🇧'],['לטביה','🇱🇻'],['ליטא','🇱🇹'],['לוקסמבורג','🇱🇺'],['מאלי','🇲🇱'],['מאלטה','🇲🇹'],['מקסיקו','🇲🇽'],['מרוקו','🇲🇦'],['מצרים','🇪🇬'],['נבחרת פלסטין','🇵🇸'],['ניגריה','🇳🇬'],['ניו זילנד','🇳🇿'],['נורווגיה','🇳🇴'],['ניקרגואה','🇳🇮'],['סין','🇨🇳'],['סלובניה','🇸🇮'],['סלובקיה','🇸🇰'],['סנגל','🇸🇳'],['ספרד','🇪🇸'],['סרביה','🇷🇸'],['סקוטלנד','🏴'],['עומאן','🇴🇲'],['עיראק','🇮🇶'],['פנמה','🇵🇦'],['פרגוואי','🇵🇾'],['פרו','🇵🇪'],['פורטוגל','🇵🇹'],['פולין','🇵🇱'],['פיליפינים','🇵🇭'],['פינלנד','🇫🇮'],['צ׳ילה','🇨🇱'],['צ׳כיה','🇨🇿'],['צרפת','🇫🇷'],['קולומביה','🇨🇴'],['קונגו','🇨🇬'],['קוסטה ריקה','🇨🇷'],['קוסובו','🇽🇰'],['קטר','🇶🇦'],['קזחסטן','🇰🇿'],['קמרון','🇨🇲'],['קנדה','🇨🇦'],['קרואטיה','🇭🇷'],['קניה','🇰🇪'],['רומניה','🇷🇴'],['רוסיה','🇷🇺'],['שוודיה','🇸🇪'],['שווייץ','🇨🇭'],['תאילנד','🇹🇭'],['תוניסיה','🇹🇳'],['טורקיה','🇹🇷']].map(([name, flag], id) => ({ id, name, flag }))
const worldCup2026 = [['מקסיקו','🇲🇽'],['דרום אפריקה','🇿🇦'],['דרום קוריאה','🇰🇷'],['צ׳כיה','🇨🇿'],['קנדה','🇨🇦'],['בוסניה והרצגובינה','🇧🇦'],['קטר','🇶🇦'],['שווייץ','🇨🇭'],['ברזיל','🇧🇷'],['מרוקו','🇲🇦'],['האיטי','🇭🇹'],['סקוטלנד','🏴'],['ארצות הברית','🇺🇸'],['פרגוואי','🇵🇾'],['אוסטרליה','🇦🇺'],['טורקיה','🇹🇷'],['גרמניה','🇩🇪'],['קוראסאו','🇨🇼'],['חוף השנהב','🇨🇮'],['אקוודור','🇪🇨'],['הולנד','🇳🇱'],['יפן','🇯🇵'],['שוודיה','🇸🇪'],['תוניסיה','🇹🇳'],['בלגיה','🇧🇪'],['מצרים','🇪🇬'],['איראן','🇮🇷'],['ניו זילנד','🇳🇿'],['ספרד','🇪🇸'],['כף ורדה','🇨🇻'],['ערב הסעודית','🇸🇦'],['אורוגוואי','🇺🇾'],['צרפת','🇫🇷'],['סנגל','🇸🇳'],['עיראק','🇮🇶'],['נורווגיה','🇳🇴'],['ארגנטינה','🇦🇷'],['אלג׳יריה','🇩🇿'],['אוסטריה','🇦🇹'],['ירדן','🇯🇴'],['פורטוגל','🇵🇹'],['קונגו הדמוקרטית','🇨🇩'],['אוזבקיסטן','🇺🇿'],['קולומביה','🇨🇴'],['אנגליה','🏴'],['קרואטיה','🇭🇷'],['גאנה','🇬🇭'],['פנמה','🇵🇦']]
worldCup2026.forEach(([name, flag]) => { if (!teams.some(team => team.name === name)) teams.push({ id: teams.length, name, flag }) })
const app = document.querySelector('#app'); const key = 'my-football-league-v1'
let selected = []; let search = ''; let league = load()
function load() { try { return JSON.parse(localStorage.getItem(key)) } catch { return null } }
function save() { localStorage.setItem(key, JSON.stringify(league)) }
function dateValue(date = new Date()) { const offset = date.getTimezoneOffset() * 60000; return new Date(date - offset).toISOString().slice(0, 10) }
function dateText(date) { return new Intl.DateTimeFormat('he-IL', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(`${date}T12:00:00`)) }
function shuffled(items) { const copy = [...items]; for (let i = copy.length - 1; i; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]] } return copy }
function fixtures(chosen, legs, startDate, weekly) {
  const rotation = shuffled(chosen); if (rotation.length % 2) rotation.push(null); const rounds = []
  for (let round = 0; round < rotation.length - 1; round++) { const games = []; for (let i = 0; i < rotation.length / 2; i++) { const home = rotation[i], away = rotation[rotation.length - 1 - i]; if (home && away) games.push({ home, away }) } rounds.push(games); rotation.splice(1, 0, rotation.pop()) }
  const all = legs === 2 ? [...rounds, ...rounds.map(games => games.map(({ home, away }) => ({ home: away, away: home })))] : rounds; const start = new Date(`${startDate}T12:00:00`)
  return all.flatMap((games, round) => { const date = new Date(start); date.setDate(start.getDate() + Math.floor(round * 7 / weekly)); return games.map((game, index) => ({ ...game, id: `${round}-${index}`, round: round + 1, date: dateValue(date), homeScore: '', awayScore: '' })) })
}
function table() {
  const rows = Object.fromEntries(league.teams.map(team => [team.id, { ...team, played: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, points: 0 }]))
  league.fixtures.forEach(game => { if (game.homeScore === '' || game.awayScore === '') return; const h = rows[game.home.id], a = rows[game.away.id], hs = +game.homeScore, as = +game.awayScore; h.played++; a.played++; h.gf += hs; h.ga += as; a.gf += as; a.ga += hs; if (hs > as) { h.wins++; a.losses++; h.points += 3 } else if (as > hs) { a.wins++; h.losses++; a.points += 3 } else { h.draws++; a.draws++; h.points++; a.points++ } })
  return Object.values(rows).sort((a,b) => b.points-a.points || (b.gf-b.ga)-(a.gf-a.ga) || b.gf-a.gf || a.name.localeCompare(b.name, 'he'))
}
function setup() {
  const list = teams.filter(team => team.name.includes(search)); const chosen = id => selected.some(team => team.id === id)
  app.innerHTML = `<main class="setup"><header><p class="eyebrow">מגרש הבית שלך</p><h1>בונים ליגה<br><em>משלכם.</em></h1><p>בחרו נבחרות, קבעו קצב, והמשחקים כבר יסתדרו בלוח.</p></header><form id="form" class="card"><div class="fields"><label>שם הליגה<input name="name" maxlength="40" placeholder="למשל: הליגה של יואב"></label><label>יום פתיחה<input name="startDate" type="date" value="${dateValue()}" required></label></div><section><div class="title"><h2><span>01</span> בוחרים נבחרות</h2><strong>${selected.length} נבחרו</strong></div><input id="search" class="search" placeholder="חיפוש נבחרת..." value="${search}"><div class="teams">${list.map(team => `<button type="button" class="team ${chosen(team.id) ? 'selected' : ''}" data-team="${team.id}"><span>${team.flag}</span>${team.name}<b>${chosen(team.id) ? '✓' : '+'}</b></button>`).join('')}</div><p class="hint">צריך לפחות 2 נבחרות. במספר אי-זוגי, נבחרת אחת תנוח בכל מחזור.</p></section><section><div class="title"><h2><span>02</span> קובעים חוקים</h2></div><div class="rules"><fieldset><legend>כמה מפגשים מול כל יריבה?</legend><label class="choice"><input type="radio" name="legs" value="1" checked> סיבוב אחד <small>מפגש אחד לכל זוג</small></label><label class="choice"><input type="radio" name="legs" value="2"> בית וחוץ <small>שני מפגשים לכל זוג</small></label></fieldset><fieldset><legend>כמה משחקים לכל נבחרת בשבוע?</legend><label class="rate"><input name="weekly" type="number" min="1" max="7" value="2"> משחקים בשבוע</label><p class="hint">כל משחקי המחזור יתקיימו באותו יום.</p></fieldset></div></section><button class="primary">מגרילים את הליגה <span>←</span></button><p id="error" class="error"></p></form></main>`
  document.querySelector('[name="name"]').placeholder = 'למשל: הליגה של תום'
  document.querySelector('.teams').insertAdjacentHTML('beforebegin', `<div class="random-picker"><label>מספר נבחרות אקראי<input id="random-count" type="number" min="2" max="${teams.length}" value="8"></label><button type="button" id="random-teams">בחירה אקראית</button></div>`)
}
function game(game) { const done = game.homeScore !== '' && game.awayScore !== ''; return `<article class="game ${done ? 'done' : ''}"><div class="home"><span>${game.home.flag}</span><b>${game.home.name}</b></div><div class="score"><input data-game="${game.id}" data-side="home" type="number" min="0" aria-label="שערי ${game.home.name}" value="${game.homeScore}"><i>:</i><input data-game="${game.id}" data-side="away" type="number" min="0" aria-label="שערי ${game.away.name}" value="${game.awayScore}"></div><div class="away"><b>${game.away.name}</b><span>${game.away.flag}</span></div></article>` }
function dashboard() {
  const groups = Object.groupBy(league.fixtures, game => game.date); const dates = Object.keys(groups).sort(); const completed = league.fixtures.filter(game => game.homeScore !== '' && game.awayScore !== '').length
  app.innerHTML = `<main class="league"><header class="league-head"><a href="#" data-new>ליגת הכדורגל שלי</a><div><p class="eyebrow">עונת משחקים</p><h1>${league.name}</h1></div><button data-new>ליגה חדשה</button></header><section class="summary"><div><span>נבחרות</span><strong>${league.teams.length}</strong></div><div><span>משחקים שהוזנו</span><strong>${completed} <small>/ ${league.fixtures.length}</small></strong></div><div><span>קצב משחקים</span><strong>${league.gamesPerWeek}<small> בשבוע</small></strong></div></section><div class="layout"><section><div class="heading"><div><p class="eyebrow">לוח המשחקים</p><h2>מתי משחקים?</h2></div></div>${dates.map(date => `<section class="matchday"><div class="date"><b>${dateText(date)}</b><small>מחזור ${groups[date][0].round}</small></div>${groups[date].map(game).join('')}</section>`).join('')}</section><aside><div class="heading"><div><p class="eyebrow">טבלת הליגה</p><h2>מי מובילה?</h2></div><small>נקודות · הפרש · שערים</small></div><div class="table"><table><thead><tr><th>#</th><th>נבחרת</th><th>מש'</th><th>נ'</th><th>ת'</th><th>ה'</th><th>שע'</th><th>הפרש</th><th>נק'</th></tr></thead><tbody>${table().map((team,i) => `<tr><td>${i+1}</td><td>${team.flag} ${team.name}</td><td>${team.played}</td><td>${team.wins}</td><td>${team.draws}</td><td>${team.losses}</td><td>${team.gf}:${team.ga}</td><td>${team.gf-team.ga > 0 ? '+' : ''}${team.gf-team.ga}</td><td><b>${team.points}</b></td></tr>`).join('')}</tbody></table></div></aside></div></main>`
}
function render() { league ? dashboard() : setup() }
app.addEventListener('input', event => { if (event.target.id === 'search') { const caret = event.target.selectionStart; search = event.target.value; setup(); const input = document.querySelector('#search'); input.focus(); input.setSelectionRange(caret, caret) } })
app.addEventListener('click', event => { const button = event.target.closest('[data-team]'); if (button) { const team = teams.find(team => team.id === +button.dataset.team); selected = selected.some(item => item.id === team.id) ? selected.filter(item => item.id !== team.id) : [...selected, team]; setup() } if (event.target.closest('[data-new]')) { event.preventDefault(); if (confirm('למחוק את הליגה הנוכחית ולהקים חדשה?')) { localStorage.removeItem(key); league = null; selected = []; render() } } })
app.addEventListener('click', event => { if (event.target.id === 'random-teams') { const count = Math.max(2, Math.min(teams.length, Number(document.querySelector('#random-count').value) || 8)); selected = shuffled(teams).slice(0, count); setup() } })
app.addEventListener('change', event => { if (!event.target.matches('[data-side]')) return; const value = event.target.value; if (value !== '' && (!Number.isInteger(+value) || +value < 0)) return; const match = league.fixtures.find(game => game.id === event.target.dataset.game); match[`${event.target.dataset.side}Score`] = value; save(); dashboard() })
app.addEventListener('submit', event => { if (event.target.id !== 'form') return; event.preventDefault(); if (selected.length < 2) { document.querySelector('#error').textContent = 'בחרו לפחות שתי נבחרות כדי להתחיל.'; return } const data = new FormData(event.target); const legs = +data.get('legs'), gamesPerWeek = +data.get('weekly'), startDate = data.get('startDate'); league = { name: data.get('name').trim() || 'הליגה שלי', teams: selected, gamesPerWeek, fixtures: fixtures(selected, legs, startDate, gamesPerWeek) }; save(); render() })
render()
